# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  benchmark-amd64:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.17', '1.18', '1.19', '1.20', '1.21' ]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go }}

    - name: Setup
      run: go mod tidy

    - name: Benchmark
      run: go test -v -bench . -benchtime 10s ./...

  benchmark-arm64:
    runs-on: self-hosted
    strategy:
      matrix:
        go: [ '1.17', '1.18', '1.19', '1.20', '1.21' ]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go }}

    - name: Setup
      run: go mod tidy

    - name: Benchmark
      run: go test -v -bench . -benchtime 10s ./...
